apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vire

resources:
  - ../../base
  - ../../vllm
  - namespace.yaml

patches:
  - target:
      kind: Deployment
      name: vire-gateway
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/optional
        value: false

images:
  - name: ghcr.io/nireo/vire
    newName: vire
    newTag: dev

configMapGenerator:
  - name: vire-models
    files:
      - models.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: vire
    app.kubernetes.io/component: gateway
