apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vire

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/nireo/vire
    newName: vire
    newTag: dev

configMapGenerator:
  - name: vire-models
    files:
      - models.json

generatorOptions:
  labels:
    app.kubernetes.io/name: vire
    app.kubernetes.io/component: gateway
