apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vire

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      kind: Deployment
      name: vire-gateway
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: -insecure-dev

images:
  - name: ghcr.io/nireo/vire
    newName: vire
    newTag: dev

configMapGenerator:
  - name: vire-models
    files:
      - models.json

generatorOptions:
  labels:
    app.kubernetes.io/name: vire
    app.kubernetes.io/component: gateway
