// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type AccountMember struct {
	AccountID string
	UserID    string
	Role      string
}

type ApiKey struct {
	ID              string
	AccountID       string
	CreatedByUserID string
	Name            string
	TokenHash       []byte
	CreatedAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type ModelPrice struct {
	ID                        string
	Model                     string
	InputRateMicroPerMillion  int64
	OutputRateMicroPerMillion int64
	CreatedAt                 pgtype.Timestamptz
}

type UsageDaily struct {
	Day                pgtype.Date
	AccountID          string
	KeyID              string
	Model              string
	RequestCount       int64
	CompleteCount      int64
	IncompleteCount    int64
	FailedCount        int64
	PromptTokens       int64
	CompletionTokens   int64
	EstimatedCostMicro int64
	PricedCount        int64
}

type UsageEvent struct {
	RequestID          string
	AccountID          string
	KeyID              string
	Model              string
	Backend            string
	PriceID            *string
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
	State              string
	HttpStatus         *int32
	PromptTokens       *int64
	CompletionTokens   *int64
	EstimatedCostMicro *int64
	RolledUpAt         pgtype.Timestamptz
}

type User struct {
	ID        string
	Email     string
	CreatedAt pgtype.Timestamptz
}
