// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountOwner = `-- name: AddAccountOwner :exec
INSERT INTO account_members(account_id, user_id, role) VALUES ($1, $2, 'owner')
`

type AddAccountOwnerParams struct {
	AccountID string
	UserID    string
}

func (q *Queries) AddAccountOwner(ctx context.Context, arg AddAccountOwnerParams) error {
	_, err := q.db.Exec(ctx, addAccountOwner, arg.AccountID, arg.UserID)
	return err
}

const beginUsage = `-- name: BeginUsage :exec
INSERT INTO usage_events(request_id, account_id, key_id, model, price_id)
VALUES ($1, $2, $3, $4,
    (SELECT id FROM model_prices WHERE model=$4
     ORDER BY created_at DESC, id DESC LIMIT 1))
`

type BeginUsageParams struct {
	RequestID string
	AccountID string
	KeyID     string
	Model     string
}

func (q *Queries) BeginUsage(ctx context.Context, arg BeginUsageParams) error {
	_, err := q.db.Exec(ctx, beginUsage,
		arg.RequestID,
		arg.AccountID,
		arg.KeyID,
		arg.Model,
	)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys(id, account_id, created_by_user_id, name, token_hash)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAPIKeyParams struct {
	ID              string
	AccountID       string
	CreatedByUserID string
	Name            string
	TokenHash       []byte
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.AccountID,
		arg.CreatedByUserID,
		arg.Name,
		arg.TokenHash,
	)
	return err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts(id, name) VALUES ($1, $2)
`

type CreateAccountParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount, arg.ID, arg.Name)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users(id, email) VALUES ($1, $2)
`

type CreateUserParams struct {
	ID    string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Email)
	return err
}

const deleteOldUsageBatch = `-- name: DeleteOldUsageBatch :execrows
DELETE FROM usage_events WHERE request_id IN (
    SELECT old.request_id FROM usage_events AS old
    WHERE old.rolled_up_at IS NOT NULL AND old.started_at < $1
    ORDER BY old.started_at LIMIT $2
)
`

type DeleteOldUsageBatchParams struct {
	StartedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) DeleteOldUsageBatch(ctx context.Context, arg DeleteOldUsageBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldUsageBatch, arg.StartedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expirePendingUsage = `-- name: ExpirePendingUsage :exec
UPDATE usage_events SET state='incomplete', finished_at=now()
WHERE state='pending' AND started_at < now() - interval '7 days'
`

func (q *Queries) ExpirePendingUsage(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expirePendingUsage)
	return err
}

const findAccountOwner = `-- name: FindAccountOwner :one
SELECT user_id FROM account_members
WHERE account_id=$1 AND role='owner'
ORDER BY user_id LIMIT 1
`

func (q *Queries) FindAccountOwner(ctx context.Context, accountID string) (string, error) {
	row := q.db.QueryRow(ctx, findAccountOwner, accountID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const finishUsage = `-- name: FinishUsage :execrows
UPDATE usage_events AS e SET
    backend=$1,
    http_status=$2,
    state=$3,
    prompt_tokens=$4::bigint,
    completion_tokens=$5::bigint,
    finished_at=now(),
    estimated_cost_micro=CASE WHEN $3='complete' THEN (
        SELECT round(($4::numeric * p.input_rate_micro_per_million +
                      $5::numeric * p.output_rate_micro_per_million) / 1000000)::bigint
        FROM model_prices AS p WHERE p.id=e.price_id
    ) ELSE NULL END
WHERE e.request_id=$6 AND e.state='pending'
`

type FinishUsageParams struct {
	Backend          string
	HttpStatus       *int32
	State            string
	PromptTokens     *int64
	CompletionTokens *int64
	RequestID        string
}

func (q *Queries) FinishUsage(ctx context.Context, arg FinishUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishUsage,
		arg.Backend,
		arg.HttpStatus,
		arg.State,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.RequestID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAPIKey = `-- name: GetActiveAPIKey :one
SELECT account_id, id, token_hash FROM api_keys
WHERE id=$1 AND revoked_at IS NULL
`

type GetActiveAPIKeyRow struct {
	AccountID string
	ID        string
	TokenHash []byte
}

func (q *Queries) GetActiveAPIKey(ctx context.Context, id string) (GetActiveAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKey, id)
	var i GetActiveAPIKeyRow
	err := row.Scan(&i.AccountID, &i.ID, &i.TokenHash)
	return i, err
}

const getDailyUsage = `-- name: GetDailyUsage :many
SELECT day, model, key_id, request_count, complete_count, incomplete_count,
       failed_count, prompt_tokens, completion_tokens, estimated_cost_micro, priced_count
FROM usage_daily WHERE account_id=$1 AND day >= $2
ORDER BY day, model, key_id
`

type GetDailyUsageParams struct {
	AccountID string
	Day       pgtype.Date
}

type GetDailyUsageRow struct {
	Day                pgtype.Date
	Model              string
	KeyID              string
	RequestCount       int64
	CompleteCount      int64
	IncompleteCount    int64
	FailedCount        int64
	PromptTokens       int64
	CompletionTokens   int64
	EstimatedCostMicro int64
	PricedCount        int64
}

func (q *Queries) GetDailyUsage(ctx context.Context, arg GetDailyUsageParams) ([]GetDailyUsageRow, error) {
	rows, err := q.db.Query(ctx, getDailyUsage, arg.AccountID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyUsageRow
	for rows.Next() {
		var i GetDailyUsageRow
		if err := rows.Scan(
			&i.Day,
			&i.Model,
			&i.KeyID,
			&i.RequestCount,
			&i.CompleteCount,
			&i.IncompleteCount,
			&i.FailedCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.EstimatedCostMicro,
			&i.PricedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at=now()
WHERE id=$1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rollupUsageBatch = `-- name: RollupUsageBatch :execrows
WITH claimed AS (
    UPDATE usage_events SET rolled_up_at=now()
    WHERE request_id IN (
        SELECT request_id FROM usage_events
        WHERE rolled_up_at IS NULL AND state <> 'pending'
        ORDER BY started_at LIMIT $1 FOR UPDATE SKIP LOCKED
    )
    RETURNING started_at::date AS day, account_id, key_id, model,
              state, prompt_tokens, completion_tokens, estimated_cost_micro
), totals AS (
    SELECT day, account_id, key_id, model,
           count(*) AS request_count,
           count(*) FILTER (WHERE state='complete') AS complete_count,
           count(*) FILTER (WHERE state='incomplete') AS incomplete_count,
           count(*) FILTER (WHERE state='failed') AS failed_count,
           COALESCE(sum(prompt_tokens), 0) AS prompt_tokens,
           COALESCE(sum(completion_tokens), 0) AS completion_tokens,
           COALESCE(sum(estimated_cost_micro), 0) AS estimated_cost_micro,
           count(*) FILTER (WHERE estimated_cost_micro IS NOT NULL) AS priced_count
    FROM claimed GROUP BY day, account_id, key_id, model
)
INSERT INTO usage_daily(day, account_id, key_id, model, request_count,
                        complete_count, incomplete_count, failed_count,
                        prompt_tokens, completion_tokens, estimated_cost_micro,
                        priced_count)
SELECT day, account_id, key_id, model, request_count, complete_count,
       incomplete_count, failed_count, prompt_tokens, completion_tokens,
       estimated_cost_micro, priced_count FROM totals
ON CONFLICT (day, account_id, key_id, model) DO UPDATE SET
    request_count=usage_daily.request_count + EXCLUDED.request_count,
    complete_count=usage_daily.complete_count + EXCLUDED.complete_count,
    incomplete_count=usage_daily.incomplete_count + EXCLUDED.incomplete_count,
    failed_count=usage_daily.failed_count + EXCLUDED.failed_count,
    prompt_tokens=usage_daily.prompt_tokens + EXCLUDED.prompt_tokens,
    completion_tokens=usage_daily.completion_tokens + EXCLUDED.completion_tokens,
    estimated_cost_micro=usage_daily.estimated_cost_micro + EXCLUDED.estimated_cost_micro,
    priced_count=usage_daily.priced_count + EXCLUDED.priced_count
`

func (q *Queries) RollupUsageBatch(ctx context.Context, limit int32) (int64, error) {
	result, err := q.db.Exec(ctx, rollupUsageBatch, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setModelPrice = `-- name: SetModelPrice :exec
INSERT INTO model_prices(id, model, input_rate_micro_per_million, output_rate_micro_per_million)
VALUES ($1, $2, $3, $4)
`

type SetModelPriceParams struct {
	ID                        string
	Model                     string
	InputRateMicroPerMillion  int64
	OutputRateMicroPerMillion int64
}

func (q *Queries) SetModelPrice(ctx context.Context, arg SetModelPriceParams) error {
	_, err := q.db.Exec(ctx, setModelPrice,
		arg.ID,
		arg.Model,
		arg.InputRateMicroPerMillion,
		arg.OutputRateMicroPerMillion,
	)
	return err
}
